baseurl = "/"
languageCode = "en-us"
title = "Shawn T. O'Neil"
# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 8
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus"
# Comment the themesDir option if you use this theme in production
#themesDir = "../.."
PygmentsCodeFences = true
pygmentsUseClassic=true

publishDir = "docs"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    #post = "/:year-:month-:day-:slug"
    post = "/:filename"


[params]
    # Tell me who you are
    author = "Shawn T. O'Neil"
    bio = "Creations, excursions, pictures, words, and colors."
    location = "Corvallis, OR"
    site_description = ""
    copyright  = "Copyright Shawn T. O'Neil 2018. Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "shawn_headshot.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    #gravatar = "you@example.com"
    logo = "css/images/logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "January, 2006"

    # Add custom assets with their paths relative to the static folder
	custom_css = ["https://unpkg.com/purecss@2.0.6/build/pure-min.css"]
	custom_js  = []


# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

#[[params.menu]]
#    before = false
#    label  = "Categories"
#    link   = "categories/"

# Enter a link for the follow button on the left
#[params.profile]
#    follow_button = "https://github.com/oneilsh"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "oneilsh"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = "oneilsh"
    instagram       = ""
    youtube         = ""
    vimeo           = "user18695315"
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "shawn-o-neil-b85244a8"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "oneilsh"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "shawntoneil"

# Enable and disable widgets for the right sidebar
[params.widgets]
    tag_cloud = true
    recent_articles = true
    #categories = true
    #tags = true
