hash:	htable.h hash.cpp list.h llist.cpp
	gpp llist.cpp hash.cpp -o hash.exe -O3 -s -Wall -Wmissing-prototypes -Wmissing-declarations -ansi -pedantic C:\DJGPP\FORTFY22\fmain.o C:\DJGPP\FORTFY22\fortify.o

